### ISSUE TITLE
Input "abc 2.0 def 3.0 ghi 4.0" displays odd printout

### ISSUE THREAD

**Issue by BlackbeardMatt** [dennis-classes/se2832-lab-01-isosceles-Lou3797#8]
The aforementioned input prints the following:

Line could not be parsed.The triangle 2.0, 3.0, 3.0 is a valid triangle. The triangle is an isosceles triangle.

**Comment by Lou3797** [comment]
I have been unable to recreate this console output with the given input. It is properly displaying this triangle is being invalid. Unsure as to why it would both display it as being valid and invalid, as it's an if else statement that decides what to string will get returned.
